runtime: python27
api_version: 1
threadsafe: true

handlers:
# - url: /styles
#   static_dir: styles
#
- url: /styles2
  static_dir: styles2

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
