runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
  
- url: /styles2
  static_dir: styles2

- url: /scripts2
  static_dir: scripts2

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
